# This is a basic workflow to help you get started with Actions

name: Publish_to_CPanel
on:
  push:
    branches:
      -main
jobs:
  FTP-Deploy-Action:
    name: Deploy_FTP
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2.1.0
      with: 
        fetch-depth: 2
      -name: Deploy_FTP
      uses: SamKirkland/FTP-Deplot-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
